
###
GET http://localhost:8000/api/get/provinsi

###
GET http://localhost:8000/api/admin/getUser

###
GET http://localhost:8000/api/get/kabupaten/3

###
GET http://localhost:8000/api/get/kecamatan/

###
GET http://localhost:8000/api/get/kelurahan/1101010002

### CreateUser Endpoint
# Mengirim request POST untuk membuat user baru
POST http://localhost:8000/api/register/auth
Content-Type: application/json

{
  "nama": "John Doe",
  "telepon": "081256518211",
  "golongan_darah": "A",
  "provinsi_id": "64",     // Ganti dengan ID provinsi yang valid
  "kabupaten_id": "6472",   // Ganti dengan ID kabupaten yang valid
  "kecamatan_id": "6472021",   // Ganti dengan ID kecamatan yang valid
  "kelurahan_id": "6472021001"    // Ganti dengan ID kelurahan yang valid
}


###
curl -X POST http://localhost:8000/send-verification-code \
-H "Content-Type: application/json" \
-d '{"phoneNumber": "081234567890", "verificationCode": "123456"}'

###
POST http://localhost:8000/api/send-verification-code
Content-Type: application/json

{
  "telepon": "081256518211",
  "verificationCode": "557889"
}

###
POST http://localhost:8000/api/register/auth
Content-Type: application/json,
withCredentials: true,
{
  "nama": "John Doe",
  "telepon": "081256518211",
  "golongan_darah": "A+",
  "provinsi_id": "64",     // Ganti dengan ID provinsi yang valid
  "kabupaten_id": "6472",   // Ganti dengan ID kabupaten yang valid
  "kecamatan_id": "6472021",   // Ganti dengan ID kecamatan yang valid
  "kelurahan_id": "6472021001",    // Ganti dengan ID kelurahan yang valid
}

###
POST http://localhost:8000/api/register/auth
Content-Type: application/json
withCredentials: true,
{
  "nama": "John Doe",
  "telepon": "081256518211",
  "golongan_darah": "A+",
  "provinsi_id": 64,
  "kabupaten_id": 6472,
  "kecamatan_id": 6472021,
  "kelurahan_id": 6472021001
}
###
POST http://localhost:8000/api/register/auth/create
Content-Type: application/json

{
    "nama": "Kapi",
    "telepon": "082253739918",
    "golongan_darah": "O",
    "ktp": "1234567890123456",
    "pekerjaan": "Engineer",
    "kelurahan_id": 6402060004
}

###
POST http://localhost:8000/api/register/auth/verify
Content-Type: application/json

{
     "code": "446590774949"
}


###
POST http://localhost:8000/api/verify/login
Content-Type: application/json

{
    "telepon" : "081256518211"
}


###
POST http://localhost:8000/api/verify/otp/login
Content-Type: application/json

{
     "code": "907749"
}

###
POST http://localhost:8000/api/logout
Content-Type: application/json


###
POST http://localhost:8000/api/verify/login
Content-Type: application/json

{
    "telepon" : "081256518211"
}

###
POST http://localhost:8000/api/verify/login
Content-Type: application/json

{
    "telepon" : "082253739918"
}

###
POST http://localhost:8000/api/verify/otp/login
Content-Type: application/json

{
    "code" : "613142"
}

###
GET http://localhost:8000/api/users/getUser

### 
POST http://localhost:8000/api/tagars/4/choose

###
DELETE http://localhost:8000/api/logout/b365f695-1cf0-4111-bb1e-6202226ab468

###
DELETE http://localhost:8000/api/logout/fb928ac6-7256-4dd0-aa33-2e7f66d6034f

###
POST http://localhost:8000/api/tagars/1/user-messages/associate
Content-Type: application/json

{
  "content": "Hello, this is a test message in cel" 
}
###
POST http://localhost:8000/api/send-message/3
Content-Type: application/json

{
  "content": " halo gess" 
}
###
GET http://localhost:8000/api/tagars/messages


###
GET http://localhost:8000/api/users/fb928ac6-7256-4dd0-aa33-2e7f66d6034f


###
GET http://localhost:8000/api/user/map



###
POST http://localhost:8000/api/check-number/telepon
Content-Type: application/json

{
  "telepon": " 081256518211" 
}


###
GET http://localhost:8000/api/admin/getUserProvinsi

###
GET http://localhost:8000/api/admin/getAkseptorProvinsi/1


###
GET http://localhost:8000/api/admin/verify_akseptor






###
PUT  http://localhost:8000/api/admin/verify_akseptor/1


###
GET http://localhost:8000/api/admin/getUserByGolongan/O


###
POST  http://localhost:8000/api/form/akseptor-send
Content-Type: application/json

{
    "nama": "John Doe",
    "telepon": "081229745461",
    "ktp": "1234567890123456",
    "golongan_darah": "A",
    "jumlah_kantong": "2",
    "alamat": "Jl. Example No. 123",
    "kelurahan_id": 6472050009,
    "tujuan_Pengajuan": "Verification purpose"
}


### 
GET http://localhost:8000/api/users/getUser/fb928ac6-7256-4dd0-aa33-2e7f66d6034f


###
GET http://localhost:8000/user
